# This setting allows you to set a default action for whether or not to test your manifest in windows sandbox
    # always - Always tests manifests
    # never - Never tests manifests
TestManifestsInSandbox: ask

# This setting allows you to define a default action for whether or not to save files to the temporary folder
    # always - Always saves files to the temporary folder
    # never - Always removes the files from the temporary folder after script execution
    # manual - Never downloads any files. All InstallerSha256 values must be entered manually
SaveToTemporaryFolder: ask

# This setting allows you to set a default action for whether or not to submit PR's
    # always - Always submits PR's automatically
    # never - Never submits PR's automatically
AutoSubmitPRs: ask

# This setting allows you to set a default action for when conflicting PRs are detected
    # always - Skips checking for conflicting PRs
    # never - Exits the script if conflicting PRs are detected
ContinueWithExistingPRs: ask

# This setting allows you to set a default action for when redirected URLs are detected
    # always - Always uses the detected destination URL
    # never - Always uses the originally entered URL
UseRedirectedURL: ask

# This setting allows you to set a default value for whether or not you have signed the Microsoft CLA
# If this value is set to true, all automatic PR's will be marked as having the CLA signed
SignedCLA: false

# This setting allows you to skip the prompt to confirm you want to use quick update mode
# If this value is set to true, the Quick Update Warning will be skipped
SuppressQuickUpdateWarning: false

# This setting allows you to require that the exact key corresponding to a menu option be pressed
# If this value is set to true, there is effectively no default action for menus
ExplicitMenuOptions: false

# This setting allows you to set a default installer locale
# Any value defined here will be set as the installer locale if one is not entered
DefaultInstallerLocale: en-US

# This setting allows for the usage of various advanced modes
# Unless you know what you are doing, it is best to leave this disabled
EnableDeveloperOptions: false

# This setting allows for the selection of which manifest version is used
# The script is not tested with all manifest versions, and stability is not guaranteed. Use with caution
OverrideManifestVersion: 1.4.0
